Bug/service logs success while event wasnt success
openartcoded/dropbox-sync pull request #23
Opened 2022-06-20 13:04 UTC by aspirio187

# Bug Fix #13 
## Description

This bug fix will be simple because the bug itself is simple.

If an event couldn't be treated properly, it is now referred as a Error and it displays the right message. The code is ready for a fail event logic (DLQ)

![image](https://user-images.githubusercontent.com/56565073/174607804-c8795628-a297-4bec-8042-a5930a19178c.png)

2022-06-20 14:40 UTC, nbittich requested changes
As you consumed the event, you lost it  in this case & you no are  no longer in sync with the backend. 
this is not enough to fix the issue. Maybe check the doc on how to deal with things like that (DLQ, ACK.NOK etc)

2022-06-24 15:39 UTC, aspirio187 commented
# Update

## Description

### Failed event redirection

There is now a redirection to a failed queue. If an event failed 5 times or more, it is sent to the DLQ.

The old way using a _delegate_ is obsolete. If I tried to send the failed event to the new queue through de  `Message_Received()` method, the app blocked and couldn't continue its task. So now 2 new tasks are started in the `Start()` method, one handling the **backend-event** messages and one handling the **dropbox-sync-failed** queue messages.

The new **`BrokerEventListerner.Start()`** method

```csharp
public void Start()
        {
            if (AmqpConnection is null) throw new NullReferenceException(nameof(AmqpConnection));

            try
            {
                _session = ((IConnection)AmqpConnection).CreateSession();
                ReceiverLink receiverLink = new ReceiverLink(_session as Session, "", _amqpCredentials.AmqpQueue);

                ReceiverTaskCancellationTokenSource = new CancellationTokenSource();
                CancellationToken token = ReceiverTaskCancellationTokenSource.Token;

                Task.Factory.StartNew(
                    () => ReceiveMessage(receiverLink, token), token);

                Task.Factory.StartNew(async () => await FailedQueueMonitoringAsync());

                // receiverLink.Start(200, Message_Received);
                _logger.LogInformation("{date} | Listening on AMQP", DateTime.Now);
            }
            catch (AmqpException e)
            {
                _logger.LogError("{date} | Couldn't create AMQP Session : {ex}", DateTime.Now, e.Message);
            }
            catch (Exception e)
            {
                _logger.LogError("{date} | An error occured while trying to create a session to the broker : {ex}",
                    DateTime.Now, e.Message);
            }
        }
```

**`BrokerEventListenenr.FailedQueueMonitoringAsync`**

```csharp
        /// <summary>
        /// Execute a timer that will trigger every 5 minutes and redirect to <see cref="CheckFailedQueue"/> method
        /// </summary>
        public async Task FailedQueueMonitoringAsync()
        {
            using var timer = new PeriodicTimer(TimeSpan.FromMinutes(10));

            while (await timer.WaitForNextTickAsync())
            {
                _logger.LogInformation("{date} | Checking the failed queue", DateTime.Now);
                CheckFailedQueue();
            }
        }
```

Every 10 minute, the service will check the _dropbox-sync-failed_ queue, process its messages and once its done, wait for the second timer call

**`BrokerEventListener.CheckFailedQueue()`**

```csharp
        /// <summary>
        /// Monitor the <c>dropbox-sync-failed</c> queue and treat every messages. If no message is received after
        /// 30 seconds, the listening process stop and it starts to process received messages. The listener is closed
        /// at the end
        /// </summary>
        public void CheckFailedQueue()
        {
            if (_session is null) throw new NullReferenceException(nameof(_session));

            _logger.LogInformation("{date} | Fail queue check started", DateTime.Now);

            List<Message> messages = new List<Message>();

            ReceiverLink? receiverLink = _session.CreateReceiver("receiver" + Guid.NewGuid(), new Source()
            {
                Address = "dropbox-sync-failed",
                Capabilities = new[]
                {
                    new Symbol("queue")
                },
                Durable = 1
            }) as ReceiverLink;

            if (receiverLink is null) throw new NullValueException(nameof(receiverLink));

            while (true)
            {
                Message? message = receiverLink.Receive(TimeSpan.FromSeconds(15));
                if (message is null)
                {
                    _logger.LogWarning("{date} | There is no more messages in failed queue!",
                        DateTime.Now);
                    break;
                }

                _logger.LogInformation("{date} | Message received from failed queue : {msg}",
                    DateTime.Now, Encoding.UTF8.GetString((byte[])message.Body));

                messages.Add(message);
            }

            foreach (Message message in messages)
            {
                if (message is null || message.Body is null)
                {
                    receiverLink.Reject(message);
                    continue;
                }

                FailedEventModel? failedEvent =
                    JsonConvert.DeserializeObject<FailedEventModel>(Encoding.UTF8.GetString((byte[])message.Body));

                if (failedEvent is null) continue;
                if (string.IsNullOrEmpty(failedEvent.MessageJson)) continue;

                EventModel? eventModel = JsonConvert.DeserializeObject<EventModel>(failedEvent.MessageJson);

                if (eventModel is null)
                {
                    receiverLink.Reject(message);
                    continue;
                }

                if (!Enum.TryParse(typeof(BrokerEvent), eventModel.EventName, out object? brokerEventParseResult))
                {
                    receiverLink.Reject(message);
                    continue;
                }

                if (brokerEventParseResult is null)
                {
                    receiverLink.Reject(message);
                    continue;
                }

                BrokerEvent eventType = (BrokerEvent)brokerEventParseResult;

                // bool redirectionResult = Task.Run<bool>(() => EventRedirection(eventType, failedEvent.MessageJson)).Result;
                bool redirectionResult = Task.Run<bool>(() =>
                    _eventManagerLocator.RedirectToManager(failedEvent.MessageJson)).Result;

                if (redirectionResult)
                {
                    _logger.LogInformation("{date} | Failed message successfully treated : \"{msg}\"",
                        DateTime.Now, failedEvent.MessageJson);

                    receiverLink.Accept(message);
                }
                else
                {
                    if (failedEvent.Attempt >= 5)
                    {
                        _logger.LogInformation("{date} | Failed message reached 5 attempts and is sent to DLQ : {msg}",
                            DateTime.Now, failedEvent.MessageJson);
                        receiverLink.Reject(message);
                    }
                    else
                    {
                        failedEvent.Attempt++;
                        Message newMessage = new Message()
                        {
                            BodySection = new Data()
                            {
                                Binary = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(failedEvent))
                            }
                        };

                        if (_session is null) throw new NullReferenceException(nameof(_session));

                        ISenderLink sender = _session.CreateSender("sender" + Guid.NewGuid(), new Target
                        {
                            Address = "dropbox-sync-failed",
                            Capabilities = new[]
                            {
                                new Symbol("queue")
                            },
                            Durable = 1
                        });

                        sender.Send(newMessage);

                        _logger.LogInformation("{date} | Message resent to failed queue : {msg}",
                            DateTime.Now, failedEvent.MessageJson);

                        sender.Close();

                        receiverLink.Accept(message);
                    }
                }
            }

            receiverLink.Close();
        }
```

### Event's manager locator

To clean the code a little bit, a locator that locates the right manager and the right method has been implemented. [...]

2022-06-27 05:49 UTC, nbittich commented on DropboxSync.UIL/BrokerEventListener.cs
> +            using var timer = new PeriodicTimer(TimeSpan.FromMinutes(10));
can be an env variable e.g FAILED_QUEUE_MONITORING_TIMER

2022-06-27 05:49 UTC, nbittich commented on DropboxSync.UIL/Managers/IDossierManager.cs
> +        [MethodEvent(typeof(DossierCreateModel), nameof(BrokerEvent.DossierCreated))]
looks cleaner indeed!

2022-06-27 06:22 UTC, nbittich approved these changes

2022-06-27 06:22 UTC, merged